# Ejercicios Numpy

In [1]:
import numpy as np

___

## Parte I

- Crea un vector con valores de 10 a 49 en pasos de 0.5.

In [2]:
mi_array=np.arange(10,49,0.5)

In [3]:
mi_array

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5,
       32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. ,
       37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5,
       43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. ,
       48.5])

- Muestra su dimensión y su tipo.

In [4]:
mi_array.ndim

1

In [5]:
mi_array.shape

(78,)

In [6]:
mi_array.dtype

dtype('float64')

- Crea un array con los números que tu elijas de dimensiones 2x3.

In [7]:
otra_array=np.zeros((2,3))

In [8]:
otra_array

array([[0., 0., 0.],
       [0., 0., 0.]])

- Redimensiona el array anterior a 3x2

In [9]:
otra_array.shape

(2, 3)

In [10]:
otra_array.reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Indexing y slicing:

- Crea un array unidimensional de 10 elemento aleatorios.

In [11]:
import random

In [12]:
array_uni=np.random.random((10))

In [13]:
array_uni

array([0.71404411, 0.3637973 , 0.43148182, 0.76497575, 0.23752933,
       0.90144206, 0.69189958, 0.75407052, 0.4417384 , 0.48523219])

- Crea un array bidimensional de 10x10 elementos aletorios.

In [14]:
array_bi=np.random.random((10,10))

In [15]:
array_bi

array([[0.56910489, 0.2937959 , 0.26784359, 0.24728428, 0.35532663,
        0.98026691, 0.07233158, 0.55668422, 0.98992576, 0.57777327],
       [0.1795227 , 0.17948924, 0.31036085, 0.47084974, 0.21960824,
        0.73294798, 0.86820833, 0.36591462, 0.85428498, 0.64514516],
       [0.21304109, 0.45824227, 0.12514217, 0.55976241, 0.19495662,
        0.82708009, 0.28098272, 0.72425612, 0.24863798, 0.7281944 ],
       [0.18583007, 0.63772713, 0.93631675, 0.1042812 , 0.38590513,
        0.99232109, 0.70314317, 0.06983831, 0.90989708, 0.26332544],
       [0.72638657, 0.26531176, 0.57135673, 0.23378755, 0.29789455,
        0.84386202, 0.7820997 , 0.85798441, 0.9847536 , 0.88239856],
       [0.83233609, 0.00761313, 0.64261654, 0.44849282, 0.22533529,
        0.74868301, 0.40820853, 0.20529722, 0.33903038, 0.39763153],
       [0.78750602, 0.56823745, 0.58555931, 0.5446499 , 0.59381181,
        0.37850938, 0.2739878 , 0.81642604, 0.04382508, 0.07732176],
       [0.18715581, 0.43471855, 0.3551890

- Accede al primer elemento y al penúltimo número de cada array. 

In [16]:
array_uni[0]

0.7140441129456647

In [17]:
array_uni[-2]

0.44173839600965803

In [18]:
array_bi[0,0]

0.5691048858502243

In [19]:
array_bi[-1,-2]

0.4468146541537925

- Array unidimensional: muestra todos los elementos en posiciones pares desde la posición 6.

In [20]:
array_uni[6::2]

array([0.69189958, 0.4417384 ])

- Array bidimensional: muestra una submatriz con las dos primeras filas y las tres primeras columnas.

In [21]:
array_bi[:2]

array([[0.56910489, 0.2937959 , 0.26784359, 0.24728428, 0.35532663,
        0.98026691, 0.07233158, 0.55668422, 0.98992576, 0.57777327],
       [0.1795227 , 0.17948924, 0.31036085, 0.47084974, 0.21960824,
        0.73294798, 0.86820833, 0.36591462, 0.85428498, 0.64514516]])

- Divide el array bidimensional en dos: uno con las 2 primera fila y otro con las siguientes filas

In [22]:
bi_a=array_bi[:2]
bi_a

array([[0.56910489, 0.2937959 , 0.26784359, 0.24728428, 0.35532663,
        0.98026691, 0.07233158, 0.55668422, 0.98992576, 0.57777327],
       [0.1795227 , 0.17948924, 0.31036085, 0.47084974, 0.21960824,
        0.73294798, 0.86820833, 0.36591462, 0.85428498, 0.64514516]])

In [23]:
bi_b=array_bi[2:]
bi_b

array([[0.21304109, 0.45824227, 0.12514217, 0.55976241, 0.19495662,
        0.82708009, 0.28098272, 0.72425612, 0.24863798, 0.7281944 ],
       [0.18583007, 0.63772713, 0.93631675, 0.1042812 , 0.38590513,
        0.99232109, 0.70314317, 0.06983831, 0.90989708, 0.26332544],
       [0.72638657, 0.26531176, 0.57135673, 0.23378755, 0.29789455,
        0.84386202, 0.7820997 , 0.85798441, 0.9847536 , 0.88239856],
       [0.83233609, 0.00761313, 0.64261654, 0.44849282, 0.22533529,
        0.74868301, 0.40820853, 0.20529722, 0.33903038, 0.39763153],
       [0.78750602, 0.56823745, 0.58555931, 0.5446499 , 0.59381181,
        0.37850938, 0.2739878 , 0.81642604, 0.04382508, 0.07732176],
       [0.18715581, 0.43471855, 0.35518909, 0.45759064, 0.312119  ,
        0.21916337, 0.74140444, 0.09622734, 0.29528151, 0.29439849],
       [0.2818357 , 0.31386126, 0.79239301, 0.65653319, 0.37604882,
        0.31340246, 0.71956088, 0.77384693, 0.01883326, 0.50129268],
       [0.25772156, 0.66649014, 0.7051941

- Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la diagonal principal valgan 5 y el resto valgan n.

In [24]:
def fun(n):
    return np.eye(n)*(5-n)+n

In [25]:
fun(6)

array([[5., 6., 6., 6., 6., 6.],
       [6., 5., 6., 6., 6., 6.],
       [6., 6., 5., 6., 6., 6.],
       [6., 6., 6., 5., 6., 6.],
       [6., 6., 6., 6., 5., 6.],
       [6., 6., 6., 6., 6., 5.]])

- Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [26]:
def chess (n, flag=False):
    array=np.zeros((n,n)) if flag else np.ones((n,n))
    array[::2, ::2] = flag
    array[1::2, 1::2] = flag
    return array

In [27]:
chess(7)

array([[0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.]])

---

## Parte II

-  Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [28]:
def num(n,m,trp):
    array=np.arange(n*m).reshape((n,m))
    if trp:
        return array.T
    else:
        return array
    

In [29]:
num(10,5,True)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

- Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [30]:
def matriz_check(matriz):
    return (matriz < 0).any()
    

In [31]:
matriz= np.random.randint(-10,10,(100,100))

In [32]:
matriz_check(matriz)

True

-  Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [33]:
def suma_neg(matrix):
    if matriz_check(matrix):
        idx = matrix < 0
        result = np.abs(matrix[idx]).sum
    else:
        result = 'No hay negativos'
    return result

In [34]:
%%timeit
suma_neg(matriz)

67.1 µs ± 614 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


---

## Parte III

- Crea un vector de 30 elementos aleatorios y calcula su media.

In [35]:
v=np.random.random((30))

In [36]:
v.mean()

0.5175709807053734

- Crea una matriz de 4x8 aleatoria y substrae la media por columnas.

In [37]:
m = np.random.randn(4,8)
print(m)

[[ 0.31200312 -1.0797967  -0.7622038   0.26003986  0.88705638  1.02150162
  -1.62737956  0.31546644]
 [ 1.74689128  0.20293539  1.18545102 -0.78661152 -1.64014857  1.43968576
  -1.47174626 -0.1685831 ]
 [ 0.960206    0.99108796  0.64481971 -0.40844279 -2.64192827 -0.42721555
   0.60573379  0.28876969]
 [ 0.51113758 -0.3518761   0.27904178 -2.22677184 -0.86634704  0.6372693
  -0.67032307 -1.03908259]]


In [38]:
m.mean(axis=1)

array([-0.08416408,  0.06348425,  0.00162882, -0.465869  ])

- Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto matricial de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

In [39]:
def enteros(n,m):
    a1 = np.random.normal(size=(n, m))
    a2 = np.random.normal(size=(m, n))
    return a1,a2,np.dot(a1,a2)
      

In [40]:
enteros(2,3)

(array([[ 1.0055924 ,  0.4616638 , -2.2865598 ],
        [-0.48552775,  0.0854756 , -0.21142846]]),
 array([[-1.88489997,  1.50465811],
        [ 0.60014763, -0.40851266],
        [-0.99467141,  1.09682743]]),
 array([[ 0.65600102, -1.18348425],
        [ 1.17677106, -0.99737167]]))

- Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la unión de los elementos únicos de ambas.

In [41]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (8,10))

In [42]:
np.unique(a)

array([1, 3, 4, 8])

In [43]:
np.unique(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
uni = np.intersect1d(a,b)
uni.sort()
uni

array([1, 3, 4, 8])

- Cree una matriz aleatoria normal de 5x10 y normalícela en media y varianza por filas y por columnas (restar la media y dividir entre la desviación típica).

In [45]:
x = np.random.rand(5, 10)

y = x  - x.mean(axis=0)
y = y / x.std(axis=0)

In [46]:
y = x  - x.mean(axis=1, keepdims=True)
y = y / x.std(axis=1, keepdims=True)

In [47]:
np.mean(y)

3.441691376337985e-17

In [48]:
np.std(y)

1.0